version: '3.8'

services:
    nginx-proxy:
        container_name: nginx-proxy
        build: ./nginx
        ports:
            - 443:443
            - 80:80
        volumes:
            - vorwerk_static_volume:/home/vorwerk/web/static/
            - vorwerk_media_volume:/home/vorwerk/web/media/
            - avental_static_volume:/home/avental/web/static/
            - avental_media_volume:/home/avental/web/media/
            - certs:/etc/nginx/certs
            - html:/usr/share/nginx/html
            - vhost:/etc/nginx/vhost.d
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - backend-network
    nginx-proxy-letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        env_file:
            - ./.env.prod.proxy-companion
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - certs:/etc/nginx/certs
            - html:/usr/share/nginx/html
            - vhost:/etc/nginx/vhost.d
            - acme:/etc/acme.sh
        networks:
            - backend-network
        depends_on:
            - nginx-proxy

networks:
    backend-network:
        external: true

volumes:
    vorwerk_static_volume:
        external: true
    vorwerk_media_volume:
        external: true
    avental_static_volume:
        external: true
    avental_media_volume:
        external: true
    certs:
    html:
    vhost:
    acme:
