version: '3.8'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.prod
        command: sh -c "gunicorn main.wsgi:application --bind 0.0.0.0:8002"
        volumes:
            - static_volume:/home/avental/web/staticfiles/
            - media_volume:/home/avental/web/media/
        expose:
            - 8002
        env_file:
            - ./.env.prod
        depends_on:
            - db
        networks:
            - vorwerk_backend-network
    db:
        image: postgres:14.1-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - 5434:5432
        env_file:
            - ./.env.db.prod
        networks:
            - vorwerk_backend-network
networks:
    vorwerk_backend-network:
        external: true
volumes:
    postgres_data:
    static_volume:
    media_volume:


