# Generated by Django 4.1.7 on 2023-05-16 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('validade', models.BooleanField(default=False)),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.upload')),
            ],
        ),
    ]
