# Generated by Django 4.2.1 on 2023-05-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_local_upload_email_upload_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='first_name',
            field=models.CharField(default='teste', max_length=80, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload',
            name='last_name',
            field=models.CharField(default='teste', max_length=80, verbose_name='Apelido'),
            preserve_default=False,
        ),
    ]
