# Generated by Django 4.2.1 on 2023-05-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_upload_first_name_alter_upload_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
