# Generated by Django 4.2.1 on 2023-05-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_upload_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
